import { Inter } from "next/font/google";
import { Provider } from "@/context/store";
import "../style/globals.css";
import "../style/globals.scss";
import "bootstrap/dist/css/bootstrap.css";
import Nav from "@/components/nav";
import Foot from "@/components/foot";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ari Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="/asset/nav/logo.png"
          type="image/png"
          sizes="32x32"
        />
      </head>
      <body className={inter.className}>
        <Provider>
          <Nav></Nav>
          {children}
          <Foot></Foot>
        </Provider>
      </body>
    </html>
  );
}
